# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f13704038b6d3181e9be7371852ae9f28fadbd26ae46ea3194bae7570859cbf571258e8064f148e3c59342afd6cf21817c2b7c376c1112dcc648cf852ef98dac

test:
  secret_key_base: 6f088b9151606e9179d2f97cc49deeb8d3bf71a26581c62ceb3a9bc7aaa7c75b54e01d07d1c933fe465b78a1b39b6c4cf1f8304307100f1c561f2d8030394a60

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
